#!/bin/bash

ln -s libopencv_calib3d.so.2.4.11	libopencv_calib3d.so
ln -s libopencv_core.so.2.4.11		libopencv_core.so
ln -s libopencv_features2d.so.2.4.11	libopencv_features2d.so
ln -s libopencv_highgui.so.2.4.11	libopencv_highgui.so
ln -s libopencv_imgproc.so.2.4.11	libopencv_imgproc.so
ln -s libopencv_legacy.so.2.4.11	libopencv_legacy.so
ln -s libopencv_ml.so.2.4.11		libopencv_ml.so
ln -s libopencv_nonfree.so.2.4.11	libopencv_nonfree.so
ln -s libopencv_objdetect.so.2.4.11	libopencv_objdetect.so
ln -s libopencv_ocl.so.2.4.11		libopencv_ocl.so
ln -s libopencv_photo.so.2.4.11		libopencv_photo.so
ln -s libopencv_stitching.so.2.4.11	libopencv_stitching.so
ln -s libopencv_superres.so.2.4.11	libopencv_superres.so

